/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "surface-container-highest": "#e1e3e4",
          "on-tertiary-fixed": "#1c1b1b",
          "primary-container": "#1cb0f6",
          "on-background": "#191c1d",
          "surface-dim": "#d9dadb",
          "on-primary-fixed-variant": "#004c6e",
          "tertiary-fixed-dim": "#c8c6c5",
          "on-secondary-fixed": "#241a00",
          "surface-tint": "#006590",
          "on-secondary": "#ffffff",
          "error-container": "#ffdad6",
          "inverse-on-surface": "#f0f1f2",
          "inverse-primary": "#88ceff",
          "background": "#f8f9fa",
          "surface-container": "#edeeef",
          "secondary-fixed-dim": "#f0c116",
          "primary-fixed-dim": "#88ceff",
          "on-primary": "#ffffff",
          "on-primary-container": "#00405d",
          "on-tertiary-container": "#3b3b3b",
          "outline-variant": "#bdc8d2",
          "outline": "#6e7881",
          "on-surface": "#191c1d",
          "on-secondary-container": "#705900",
          "tertiary": "#5f5e5e",
          "surface-variant": "#e1e3e4",
          "tertiary-container": "#a7a5a5",
          "surface-container-lowest": "#ffffff",
          "secondary-container": "#ffcf2a",
          "surface-white": "#FFFFFF",
          "on-secondary-fixed-variant": "#574400",
          "surface-bright": "#f8f9fa",
          "on-tertiary-fixed-variant": "#474746",
          "footer-background": "#F3C41B",
          "on-surface-text": "#1A1A1A",
          "primary": "#006590",
          "on-error": "#ffffff",
          "footer-on-surface": "#000000",
          "on-error-container": "#93000a",
          "surface-container-high": "#e7e8e9",
          "secondary-fixed": "#ffe08a",
          "secondary": "#745b00",
          "surface": "#f8f9fa",
          "tertiary-fixed": "#e5e2e1",
          "surface-container-low": "#f3f4f5",
          "primary-fixed": "#c8e6ff",
          "on-primary-fixed": "#001e2e",
          "index-number-gray": "#E5E5E5",
          "error": "#ba1a1a",
          "on-tertiary": "#ffffff",
          "on-surface-variant": "#3e4850",
          "inverse-surface": "#2e3132"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "container-max": "1200px",
          "nav-height": "64px",
          "section-padding": "80px",
          "margin-mobile": "16px",
          "margin-desktop": "auto",
          "gutter": "24px"
      },
      "fontFamily": {
          "body-lg": ["Inter", "sans-serif"],
          "index-bg": ["Nunito Sans", "sans-serif"],
          "title-lg": ["Inter", "sans-serif"],
          "body-md": ["Inter", "sans-serif"],
          "display-lg": ["Nunito Sans", "sans-serif"],
          "headline-lg": ["Nunito Sans", "sans-serif"],
          "headline-lg-mobile": ["Nunito Sans", "sans-serif"],
          "label-lg": ["Inter", "sans-serif"],
          "headline-md": ["Nunito Sans", "sans-serif"]
      },
      "fontSize": {
          "body-lg": ["16px", {"lineHeight": "24px", "letterSpacing": "0.5px", "fontWeight": "400"}],
          "index-bg": ["72px", {"lineHeight": "72px", "fontWeight": "800"}],
          "title-lg": ["22px", {"lineHeight": "28px", "fontWeight": "500"}],
          "body-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.25px", "fontWeight": "400"}],
          "display-lg": ["57px", {"lineHeight": "64px", "letterSpacing": "-0.25px", "fontWeight": "700"}],
          "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
          "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
          "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.1px", "fontWeight": "500"}],
          "headline-md": ["28px", {"lineHeight": "36px", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
